@startuml

package 参加者集約 {
  class 参加者 {
    +参加者ID
    +参加者名
    +メールアドレス
    +在籍ステータス
  }
  note right of 参加者: メールアドレスは重複不可\n在崎ステータスは「在籍中」「休会中」「退会済」\n在籍ステータスが「在籍中」ではない場合、どのチームにもペアにも所属してはいけない
}

package チーム集約 {
  class チーム {
    +チームID
    +チーム名
  }

  note right of チーム: チームの名前は1,2,3,4のような数字でなければいけない\nチームの名前は重複不可\nチームの名前は3文字以下でなければいけない\nチームには最低でも参加者が3名いなければならない

  class チームメンバー {
    +チームID
    +参加者ID
  }
}

package ペア集約 {
  class ペア {
    +ペアID
    +チームID
    +ペア名
  }

  note right of ペア: ペア名はa,b,c,d,eのような英文字でなければいけない\nペア名は1文字でなければいけない\nペアは必ず同じチームの参加者から選ばれる

  class ペアメンバー {
    +ペアID
    +参加者ID
  }
}

package 課題集約 {
  class 課題 {
    +課題ID
    +課題名
  }

  class 課題進捗 {
    +課題ID
    +参加者ID
    +進捗ステータス
  }

  note right of 課題進捗: 進捗ステータスは「未着手」「レビュー待ち」「完了」\n進捗ステータスはいつでも変更可能\nただし一度「完了」にした進捗ステータスを「レビュー待ち」「未着手」に戻すことはできない\n進捗ステータスを変更できるのは、課題の所有者だけ
}

チーム "1" -- "0..n" チームメンバー
チーム "1" <-u- "0..n" ペア
ペア "1" -- "0..n" ペアメンバー
参加者 "1" <-- "0..n" ペアメンバー
参加者 "1" <-- "0..n" チームメンバー
参加者 "1" <-- "0..n" 課題進捗
課題 "1" -- "0..n" 課題進捗

@enduml
