@startuml

package 参加者集約 {
  class 参加者 {
    +参加者ID
    +参加者名
    +メールアドレス
    +在籍ステータス
  }
}

package チーム集約 {
  class チーム {
    +チームID
    +チーム名
  }

  class チームメンバー {
    +チームID
    +参加者ID
  }
}

package ペア集約 {
  class ペア {
    +ペアID
    +チームID
    +ペア名
  }

  class ペアメンバー {
    +ペアID
    +参加者ID
  }
}

package 課題集約 {
  class 課題 {
    +課題ID
    +課題名
  }

  class 課題進捗 {
    +課題ID
    +参加者ID
    +進捗ステータス
  }
}

チーム "1" -- "0..n" チームメンバー
チーム "1" <-u- "0..n" ペア
ペア "1" -- "0..n" ペアメンバー
参加者 "1" <-- "0..n" ペアメンバー
参加者 "1" <-- "0..n" チームメンバー
参加者 "1" <-- "0..n" 課題進捗
課題 "1" -- "0..n" 課題進捗

@enduml
