@startuml
entity product as "product\n商品" {
  *product_id :int [PK]
  --
  *product_type_id :int [FK]
  name :varchar [商品名]
  consumption_tax :int [消費税]
  tax_excluded_amount :int [税抜き価格]
  tax_included_amount :int [税込価格]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

entity product_type as "product_type\n商品種別" {
  *product_type_id:int [PK]
  --
  name :varchar [商品種別名]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

note right: セットメニュー、お好み寿司...

entity order as "order\n注文" {
  *order_id :int [PK]
  --
  status :int [注文状態]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

entity order_detail as "order_detail\n注文詳細" {
  *order_detail_id :int [PK]
  --
  *order_id :int [FK]
  *product_id :int [FK]
  consumption_tax :int [消費税]
  tax_excluded_unit_cost :int [税抜き単価]
  tax_included_unit_cost :int [税込み単価]
  number :int [注文数]
  add_wasabi :bool [さび入り]
  size :tinyint [サイズ種別]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

product ||-d-|| product_type
order ||-d-|{ order_detail
product ||-r-|{ order_detail


@enduml