@startuml

entity single_menu as "single_menu\n個別メニュー" {
  *single_menu_id :int [PK]
  --
  name :varchar [メニュー名]
  consumption_tax :int [消費税]
  tax_excluded_amount :int [税抜き価格]
  tax_included_amount :int [税込価格]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
  deleted_at :datetime [削除日]
}

entity order_single_menu as "order_single_menu\n注文 - 個別メニュー" {
  *order_single_menu_id :int [PK]
  --
  *order_detail_id :int [FK]
  *single_menu_id :int [FK]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

entity set_menu as "set_menu\nセットメニュー" {
  *set_menu_id :int [PK]
  --
  name :varchar [メニュー名]
  consumption_tax :int [消費税]
  tax_excluded_amount :int [税抜き価格]
  tax_included_amount :int [税込価格]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
  deleted_at :datetime [削除日]
}

entity order_set_menu as "order_set_menu\n注文 - セットメニュー" {
  *order_set_menu_id :int [PK]
  --
  *order_detail_id :int [FK]
  *set_menu_id :int [FK]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

entity order as "order\n注文" {
  *order_id :int [PK]
  --
  tax_excluded_order_amount :int [税抜き注文金額]
  tax_included_order_amount :int [税込み注文金額]
  status :int [注文状態]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

entity order_detail as "order_detail\n注文詳細" {
  *order_detail_id :int [PK]
  --
  *order_id :int [FK]
  number :int [注文数]
  add_wasabi :bool [さび入り]
  type :tinyint [注文種別]
  created_at :datetime [作成日]
  updated_at :datetime [更新日]
}

note right: 注文種別 Ex) 1:個別メニュー 2: セットメニュー

order ||-d-|{ order_detail
order_detail ||--o{ order_single_menu
order_detail ||--o{ order_set_menu
order_single_menu }o--|| single_menu
order_set_menu }o--|| set_menu

@enduml